on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Cache gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}

    - name: Setup Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update -qqy
        sudo apt-get -qqy install google-chrome-stable

    - name: Install dependencies
      run: |
        sudo apt-get -yqq install libpq-dev
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run tests
      env:
        RAILS_ENV: test
        DATABASE_URL: sqlite3://db/test.sqlite3
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load
        bundle exec rspec

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
